# Kong Nginx 自定义配置
# lua_shared_dict 配置

lua_code_cache on;
lua_shared_dict jwt_cache_dict 200m;
lua_shared_dict ipc_shared_dict_jwt 100m;
lua_shared_dict api_cache_dict 200m;
lua_shared_dict ipc_shared_dict_api 100m;
